export const footerResponse = [
  {
    id: "d0e7751b-1f4e-4dde-8156-2ca281a4765e",
    siteNavigation: [
      {
        id: 1,
        label: "ABOUT US",
        link: "",
        type: "1",
        showImage: false,
        imageCta: "#",
        imageUrl: "",
        sections: [],
        linkShowAll: {
          show: true,
          label: "",
        },
        tabValues: [
          {
            tabValue: "",
          },
        ],
        showTabs: false,
        sequence: 1,
        section: [
          {
            label: "Blog",
            isLeftAlign: true,
            linkShowAll: {
              show: false,
              label: "",
            },
            link: [],
            sequence: 2,
            labelLink: "/blog",
          },
          {
            label: "Our story",
            isLeftAlign: true,
            linkShowAll: {
              show: false,
              label: "",
            },
            link: [],
            sequence: 2,
            labelLink: "/about-us",
          },
          {
            label: "Our stores",
            isLeftAlign: true,
            linkShowAll: {
              show: false,
              label: "",
            },
            link: [],
            sequence: 3,
            labelLink: "/viewings",
          },
          {
            label: "Customers reviews",
            isLeftAlign: true,
            linkShowAll: {
              show: false,
              label: "",
            },
            link: [],
            sequence: 4,
            labelLink: "/customer-reviews",
          },
          {
            label: "Certifications & awards",
            isLeftAlign: true,
            linkShowAll: {
              show: false,
              label: "",
            },
            link: [],
            sequence: 5,
            labelLink: "#",
          },
        ],
      },
      {
        id: 1,
        label: "CUSTOMER CARE",
        link: "",
        type: "1",
        showImage: false,
        imageCta: "#",
        imageUrl: "",
        sections: [],
        linkShowAll: {
          show: true,
          label: "",
        },
        tabValues: [
          {
            tabValue: "",
          },
        ],
        showTabs: false,
        sequence: 2,
        section: [
          {
            label: "Free delivery & returns",
            isLeftAlign: true,
            linkShowAll: {
              show: false,
              label: "",
            },
            link: [],
            sequence: 1,
            labelLink: "/customer-care/free-delivery",
          },
          {
            label: "Refunds policy",
            isLeftAlign: true,
            linkShowAll: {
              show: false,
              label: "",
            },
            link: [],
            sequence: 2,
            labelLink: "/customer-care/returns-policy",
          },
          {
            label: "Manufacturing lifetime warranty",
            isLeftAlign: true,
            linkShowAll: {
              show: false,
              label: "",
            },
            link: [],
            sequence: 3,
            labelLink: "/customer-care/lifetime-manufacturing-guarantee",
          },
          {
            label: "0% APR finance",
            isLeftAlign: true,
            linkShowAll: {
              show: false,
              label: "",
            },
            link: [],
            sequence: 4,
          },
          {
            label: "Free resizing service",
            isLeftAlign: true,
            linkShowAll: {
              show: false,
              label: "",
            },
            link: [],
            sequence: 5,
            labelLink: "/free-resizing",
          },
          {
            label: "Valuations",
            isLeftAlign: true,
            linkShowAll: {
              show: false,
              label: "",
            },
            link: [],
            sequence: 6,
            labelLink: "/valuations",
          },
          {
            label: "FAQs",
            isLeftAlign: true,
            linkShowAll: {
              show: false,
              label: "",
            },
            link: [],
            sequence: 7,
            labelLink: "/education/faqs",
          },
        ],
      },
      {
        id: 1,
        label: "JEWELLERY GUIDES",
        link: "",
        type: "1",
        showImage: false,
        imageCta: "#",
        imageUrl: "",
        sections: [],
        linkShowAll: {
          show: true,
          label: "",
        },
        tabValues: [
          {
            tabValue: "",
          },
        ],
        showTabs: false,
        sequence: 3,
        section: [
          {
            label: "Diamonds guide",
            isLeftAlign: true,
            linkShowAll: {
              show: false,
              label: "",
            },
            link: [],
            sequence: 1,
          },
          {
            label: "Metals guide",
            isLeftAlign: true,
            linkShowAll: {
              show: false,
              label: "",
            },
            link: [],
            sequence: 2,
          },
          {
            label: "Gemstones guide",
            isLeftAlign: true,
            linkShowAll: {
              show: false,
              label: "",
            },
            link: [],
            sequence: 3,
          },
          {
            label: "Ring size guide",
            isLeftAlign: true,
            linkShowAll: {
              show: false,
              label: "",
            },
            link: [],
            sequence: 4,
          },
          {
            label: "Jewellery care",
            isLeftAlign: true,
            linkShowAll: {
              show: false,
              label: "",
            },
            link: [],
            sequence: 5,
          },
          {
            label: "Jewellery care",
            isLeftAlign: true,
            linkShowAll: {
              show: false,
              label: "",
            },
            link: [],
            sequence: 6,
          },
        ],
      },
      {
        id: 1,
        label: "STORES",
        link: "",
        type: "1",
        showImage: false,
        imageCta: "#",
        imageUrl: "",
        sections: [],
        linkShowAll: {
          show: true,
          label: "",
        },
        tabValues: [
          {
            tabValue: "",
          },
        ],
        showTabs: false,
        sequence: 4,
        section: [
          {
            label: "London",
            isLeftAlign: true,
            linkShowAll: {
              show: false,
              label: "",
            },
            link: [],
            sequence: 2,
            labelLink: "/customer-care/viewings/london",
          },
          {
            label: "Manchester",
            isLeftAlign: true,
            linkShowAll: {
              show: false,
              label: "",
            },
            link: [],
            sequence: 2,
            labelLink: "/customer-care/viewings/manchester",
          },
          {
            label: "Leeds",
            isLeftAlign: true,
            linkShowAll: {
              show: false,
              label: "",
            },
            link: [],
            sequence: 3,
            labelLink: "/customer-care/viewings/leeds",
          },
          {
            label: "Liverpool",
            isLeftAlign: true,
            linkShowAll: {
              show: false,
              label: "",
            },
            link: [],
            sequence: 3,
            labelLink: "/customer-care/viewings/liverpool",
          },
          {
            label: "Sheffield",
            isLeftAlign: true,
            linkShowAll: {
              show: false,
              label: "",
            },
            link: [],
            sequence: 5,
            labelLink: "/customer-care/viewings/sheffield",
          },
          {
            label: "Glasgow",
            isLeftAlign: true,
            linkShowAll: {
              show: false,
              label: "",
            },
            link: [],
            sequence: 6,
            labelLink: "/customer-care/viewings/glasgow",
          },
          {
            label: "Nottingham",
            isLeftAlign: true,
            linkShowAll: {
              show: false,
              label: "",
            },
            link: [],
            sequence: 7,
            labelLink: "/customer-care/viewings/nottingham",
          },
          {
            label: "Edinburgh",
            isLeftAlign: true,
            linkShowAll: {
              show: false,
              label: "",
            },
            link: [],
            sequence: 2,
            labelLink: "/customer-care/viewings/edinburgh",
          },
          {
            label: "Birmingham",
            isLeftAlign: true,
            linkShowAll: {
              show: false,
              label: "",
            },
            link: [],
            sequence: 4,
            labelLink: "/customer-care/viewings/birmingham",
          },
          {
            label: "Newcastle",
            isLeftAlign: true,
            linkShowAll: {
              show: false,
              label: "",
            },
            link: [],
            sequence: 8,
            labelLink: "/customer-care/viewings/newcastle",
          },
          {
            label: "Belfast",
            isLeftAlign: true,
            linkShowAll: {
              show: false,
              label: "",
            },
            link: [],
            sequence: 8,
            labelLink: "/customer-care/viewings/belfast",
          },
          {
            label: "Cardiff",
            isLeftAlign: true,
            linkShowAll: {
              show: false,
              label: "",
            },
            link: [],
            sequence: 10,
            labelLink: "/customer-care/viewings/cardiff",
          },
          {
            label: "Chester",
            isLeftAlign: true,
            linkShowAll: {
              show: false,
              label: "",
            },
            link: [],
            sequence: 12,
            labelLink: "/customer-care/viewings/chester",
          },
          {
            label: "Norwich",
            isLeftAlign: true,
            linkShowAll: {
              show: false,
              label: "",
            },
            link: [],
            sequence: 14,
            labelLink: "/customer-care/viewings/norwich",
          },
        ],
      },
    ],
    section: [],
    storeId: "8a9fb423-7019-48ff-8b78-68250cdd8190",
    type: "footer",
    name: "Footer ",
    siteLogo: "/assets/images/austen-and-blake-logo.png",
    newsletterTitle: "",
    copyright: "© 2024 Austen & Blake. All Rights Reserved.",
    socialMedias: [
      {
        id: 1,
        iconsLink:
          "/assets/images/austen-and-blake/social-media/ab-instagram-icon.png",
        alt: "instagram",
        sequence: 1,
        link: "https://www.instagram.com/austenandblake/",
      },
      {
        id: 1,
        iconsLink:
          "/assets/images/austen-and-blake/social-media/ab-facebook-icon.png",
        alt: "facebook",
        sequence: 2,
        link: "https://www.facebook.com/austenandblake",
      },
      {
        id: 1,
        iconsLink:
          "/assets/images/austen-and-blake/social-media/ab-twitter-icon.png",
        alt: "twitter",
        sequence: 3,
        link: "https://www.twitter.com/austenandblake",
      },
    ],
    certificates: [
      {
        id: 1,
        iconsLink: "/assets/images/icons/ELEL_icon.png",
        alt: "Elle",
        sequence: 1,
        link: "test",
      },
      {
        id: 1,
        iconsLink: "/assets/images/icons/professional-jeweller.png",
        alt: "professional-jeweller",
        sequence: 2,
      },
      {
        id: 1,
        iconsLink: "/assets/images/icons/refinery29.png",
        alt: "refinery29",
        sequence: 3,
      },
      {
        id: 1,
        iconsLink: "/assets/images/icons/guides-for-brides.png",
        alt: "guides for brides",
        sequence: 4,
      },
      {
        id: 1,
        iconsLink: "/assets/images/icons/ok.png",
        alt: "Ok",
        sequence: 5,
      },
      {
        id: 1,
        iconsLink: "/assets/images/icons/vogue.png",
        alt: "Vogue",
        sequence: 6,
      },
    ],
    otherLinks: [
      {
        id: 1,
        label: "Privacy Policy",
        link: "/privacy-policy",
        sequence: 1,
      },
      {
        id: 1,
        label: "Cookies Policy",
        link: "/cookie-policy",
        sequence: 2,
      },
      {
        id: 1,
        label: "Terms & Conditions",
        link: "/terms-and-condition",
        sequence: 3,
      },
      {
        id: 1,
        label: "Sitemap",
        link: "#",
        sequence: 4,
      },
    ],
    isContactUs: true,
    defaultSelect: true,
    isDefault: true,
  },
];
