export const headerResponse = [
  {
    name: "Header ",
    storeId: "c7180f79-28cb-4d87-a34e-de2a87ac993e",
    type: "header",
    isContactUs: false,
    siteNavigation: [
      {
        id: 1,
        label: "Engagement rings",
        link: "/choose-engagement-rings",
        type: "1",
        showImage: true,
        sections: [],
        linkShowAll: {
          show: true,
          label: "",
        },
        tabValues: [
          {
            tabValue: "",
          },
        ],
        showTabs: false,
        sequence: 1,
        section: [
          {
            label: "Design your own engagement ring",
            isLeftAlign: true,
            isClickable: true,
            linkShowAll: {
              show: true,
              label: "View all engagement rings",
              labelLink: "/choose-your-setting",
            },
            link: [
              {
                label: "Start with the setting",
                showIcon: false,
                iconUrl: "#",
                link: "/assets/icons/raw-svgs/design-settings.svg",
                isMobile: true,
                sequence: 1,
                titleUrl: "/choose-your-setting",
              },
              {
                label: "Start with a natural diamond ",
                showIcon: true,
                iconUrl: "#",
                link: "/assets/icons/raw-svgs/black-diamond.svg",
                isMobile: true,
                sequence: 2,
                titleUrl: "#",
              },
              {
                label: "Start with a lab grown diamond",
                showIcon: true,
                iconUrl: "#",
                link: "/assets/icons/raw-svgs/grey-diamond.svg",
                isMobile: true,
                sequence: 3,
                titleUrl: "#",
              },
              {
                label: "Bestsellers",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 4,
                titleUrl: "#",
              },
              {
                label: "New arrivals",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 5,
                titleUrl: "#",
              },
              {
                label: "Gemstone",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 6,
                titleUrl: "#",
              },
              {
                label: "Quick delivery",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 7,
                titleUrl: "#",
              },
              {
                label: "Bespoke design   ",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 8,
                titleUrl: "#",
              },
              {
                label: "",
                showIcon: true,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 9,
              },
            ],
            sequence: 1,
            labelLink: "/labellink",
          },
          {
            label: "Shop by style",
            isLeftAlign: true,
            isClickable: true,
            linkShowAll: {
              show: true,
              label: "View all styles",
              labelLink: "#",
            },
            link: [
              {
                label: "Solitare",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 1,
                titleUrl: "/engagement-rings/solitaire",
              },
              {
                label: "Stacking",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 2,
                titleUrl: "/engagement-rings/stacking",
              },
              {
                label: "Everyday",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 3,
                titleUrl: "/engagement-rings/product-listing",
              },
              {
                label: "Eternity",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 4,
                titleUrl: "/engagement-rings/product-listing",
              },
              {
                label: "Anniversary",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 5,
                titleUrl: "/engagement-rings/product-listing",
              },
              {
                label: "Promise",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 6,
                titleUrl: "/engagement-rings/product-listing",
              },
              {
                label: "Two stone",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 7,
                titleUrl: "/engagement-rings/two-stone",
              },
              {
                label: "Statement",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 8,
                titleUrl: "/engagement-rings/product-listing",
              },
              {
                label: "Coloured diamonds",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 9,
                titleUrl: "/engagement-rings/coloured-diamonds",
              },
            ],
            sequence: 2,
            labelLink: "#labelLink",
          },
          {
            label: "Shop by shape",
            isLeftAlign: true,
            isClickable: true,
            linkShowAll: {
              show: true,
              label: "View all shape",
              labelLink: "#",
            },
            link: [
              {
                label: "Round",
                showIcon: true,
                iconUrl: "#",
                link: "/assets/icons/raw-svgs/round-shape.svg",
                isMobile: true,
                sequence: 1,
                titleUrl: "/engagement-rings/round",
              },
              {
                label: "Oval",
                showIcon: true,
                iconUrl: "#",
                link: "/assets/icons/raw-svgs/oval.svg",
                isMobile: true,
                sequence: 2,
                titleUrl: "/engagement-rings/oval",
              },
              {
                label: "Emerald",
                showIcon: true,
                iconUrl: "#",
                link: "/assets/icons/raw-svgs/emerald-shape.svg",
                isMobile: true,
                sequence: 3,
                titleUrl: "/engagement-rings/emerald",
              },
              {
                label: "Pear",
                showIcon: true,
                iconUrl: "#",
                link: "/assets/icons/raw-svgs/pear-shape.svg",
                isMobile: true,
                sequence: 4,
                titleUrl: "/engagement-rings/pear",
              },
              {
                label: "Cushion",
                showIcon: true,
                iconUrl: "#",
                link: "/assets/icons/raw-svgs/cushion-shape.svg",
                isMobile: true,
                sequence: 5,
                titleUrl: "/engagement-rings/cushion",
              },
              {
                label: "Marquise",
                showIcon: true,
                iconUrl: "#",
                link: "/assets/icons/raw-svgs/marquise-shape.svg",
                isMobile: true,
                sequence: 6,
                titleUrl: "/engagement-rings/marquise",
              },
            ],
            sequence: 3,
            labelLink: "#",
          },
          {
            label: "Shop by metal",
            isLeftAlign: false,
            isClickable: true,
            linkShowAll: {
              show: true,
              label: "View all metals",
              labelLink: "#",
            },
            link: [
              {
                label: "White gold",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 1,
                titleUrl: "#",
              },
              {
                label: "Yellow gold",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 2,
                titleUrl: "#",
              },
              {
                label: "Rose gold",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 3,
                titleUrl: "#",
              },
              {
                label: "Platinum",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 4,
                titleUrl: "/engagement-rings/platinum",
              },
            ],
            sequence: 4,
            labelLink: "#",
          },
        ],
        imageCta: "/engagement-rings",
        additionalLink: [
          {
            label: "Engagement ring guides",
            link: "/education/engagement-ring-guide",
            icon: false,
            sequence: 1,
          },
          {
            label: "Get expert advice",
            link: "#",
            sequence: 2,
            icon: false,
          },
        ],
        imageUrl: "/assets/images/megamenu-banner.png",
      },
      {
        id: 1,
        label: "Diamond Rings",
        link: "/diamond-rings",
        type: "1",
        showImage: true,
        imageUrl: "/assets/images/megamenu-banner.png",
        linkShowAll: {
          show: true,
          label: "",
        },
        tabValues: [
          {
            tabValue: "",
          },
        ],
        showTabs: false,
        sequence: 2,
        section: [
          {
            label: "Design your own diamond ring",
            isLeftAlign: true,
            isClickable: true,
            linkShowAll: {
              show: true,
              label: "View all diamond rings",
              labelLink: "#",
            },
            link: [
              {
                label: "Start with the setting",
                showIcon: true,
                iconUrl: "#",
                link: "/assets/icons/raw-svgs/design-settings.svg",
                isMobile: true,
                sequence: 1,
                titleUrl: "#",
              },
              {
                label: "Start with a natural diamond ",
                showIcon: true,
                iconUrl: "#",
                link: "/assets/icons/raw-svgs/black-diamond.svg",
                isMobile: true,
                sequence: 2,
                titleUrl: "#",
              },
              {
                label: "Start with a lab grown diamond",
                showIcon: true,
                iconUrl: "#",
                link: "/assets/icons/raw-svgs/grey-diamond.svg",
                isMobile: true,
                sequence: 3,
                titleUrl: "#",
              },
              {
                label: "Bestsellers",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 4,
                titleUrl: "#",
              },
              {
                label: "New arrivals",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 5,
                titleUrl: "#",
              },
              {
                label: "Gemstone",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 6,
                titleUrl: "#",
              },
              {
                label: "Quick delivery",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 7,
                titleUrl: "#",
              },
              {
                label: "Bespoke design   ",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 8,
                titleUrl: "#",
              },
              {
                label: "",
                showIcon: true,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 9,
              },
            ],
            sequence: 1,
            labelLink: "#",
          },
          {
            label: "Shop by style",
            isLeftAlign: true,
            isClickable: true,
            linkShowAll: {
              show: true,
              label: "View all styles",
              labelLink: "#",
            },
            link: [
              {
                label: "Solitare",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 1,
                titleUrl: "/diamond-rings/classic-solitaire",
              },
              {
                label: "Stacking",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 2,
                titleUrl: "/diamond-rings/stacking",
              },
              {
                label: "Everyday",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 3,
                titleUrl: "#",
              },
              {
                label: "Eternity",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 4,
                titleUrl: "#",
              },
              {
                label: "Anniversary",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 5,
                titleUrl: "#",
              },
              {
                label: "Promise",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 6,
                titleUrl: "#",
              },
              {
                label: "Two stone",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 7,
                titleUrl: "/diamond-rings/two-stone",
              },
              {
                label: "Statement",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 8,
                titleUrl: "#",
              },
              {
                label: "Coloured diamonds",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 9,
                titleUrl: "#",
              },
            ],
            sequence: 2,
            labelLink: "#",
          },
          {
            label: "Shop by shape",
            isLeftAlign: true,
            isClickable: true,
            linkShowAll: {
              show: true,
              label: "View all shape",
              labelLink: "#",
            },
            link: [
              {
                label: "Round",
                showIcon: true,
                iconUrl: "#",
                link: "/assets/icons/raw-svgs/round-shape.svg",
                isMobile: true,
                sequence: 1,
                titleUrl: "/diamond-rings/round",
              },
              {
                label: "Oval",
                showIcon: true,
                iconUrl: "#",
                link: "/assets/icons/raw-svgs/oval.svg",
                isMobile: true,
                sequence: 2,
                titleUrl: "/diamond-rings/oval",
              },
              {
                label: "Emerald",
                showIcon: true,
                iconUrl: "#",
                link: "/assets/icons/raw-svgs/emerald-shape.svg",
                isMobile: true,
                sequence: 3,
                titleUrl: "/diamond-rings/emerald",
              },
              {
                label: "Pear",
                showIcon: true,
                iconUrl: "#",
                link: "/assets/icons/raw-svgs/pear-shape.svg",
                isMobile: true,
                sequence: 4,
                titleUrl: "/diamond-rings/pear",
              },
              {
                label: "Cushion",
                showIcon: true,
                iconUrl: "#",
                link: "/assets/icons/raw-svgs/cushion-shape.svg",
                isMobile: true,
                sequence: 5,
                titleUrl: "/diamond-rings/cushion",
              },
              {
                label: "Marquise",
                showIcon: true,
                iconUrl: "#",
                link: "/assets/icons/raw-svgs/marquise-shape.svg",
                isMobile: true,
                sequence: 6,
                titleUrl: "/diamond-rings/marquise",
              },
            ],
            sequence: 3,
            labelLink: "#",
          },
          {
            label: "Shop by metal",
            isLeftAlign: true,
            isClickable: true,
            linkShowAll: {
              show: true,
              label: "View all metals",
              labelLink: "#",
            },
            link: [
              {
                label: "White gold",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 1,
                titleUrl: "#",
              },
              {
                label: "Yellow gold",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 2,
                titleUrl: "#",
              },
              {
                label: "Rose gold",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 3,
                titleUrl: "#",
              },
              {
                label: "Platinum",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 4,
                titleUrl: "#",
              },
            ],
            sequence: 4,
            labelLink: "#",
          },
        ],
        imageCta: "#",
        additionalLink: [
          {
            label: "Diamond ring guide",
            link: "/education/diamond-guide",
            sequence: 1,
            icon: false,
          },
          {
            label: "Get expert advice",
            link: "#",
            sequence: 2,
            icon: false,
          },
        ],
      },
      {
        id: 1,
        label: "Wedding Rings",
        link: "/wedding-rings",
        type: "1",
        showImage: true,
        imageCta: "#",
        imageUrl: "/assets/images/megamenu-banner.png",
        sections: [],
        linkShowAll: {
          show: true,
          label: "",
        },
        tabValues: [
          {
            tabValue: "WOMEN",
          },
          {
            tabValue: "MEN",
          },
        ],
        showTabs: true,
        sequence: 3,
        section: [
          {
            label: "Shop by style",
            isLeftAlign: true,
            isClickable: true,
            linkShowAll: {
              show: true,
              label: "View all styles",
              labelLink: "#",
            },
            link: [
              {
                label: "Plain",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 1,
                titleUrl: "#",
              },
              {
                label: "Diamond",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 2,
                titleUrl: "#",
              },
              {
                label: "Shaped",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 3,
                titleUrl: "#",
              },
              {
                label: "Gemstone",
                showIcon: true,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 4,
                titleUrl: "#",
              },
              {
                label: "Textured",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 5,
                titleUrl: "#",
              },
            ],
            sequence: 1,
            tabs: "WOMEN",
          },
          {
            label: "Shop by metal",
            isLeftAlign: true,
            linkShowAll: {
              show: true,
              label: "View all metals",
              labelLink: "#",
            },
            link: [
              {
                label: "Silver",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 1,
                titleUrl: "#",
              },
              {
                label: "White gold",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 2,
                titleUrl: "#",
              },
              {
                label: "Yellow gold",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 3,
                titleUrl: "#",
              },
              {
                label: "Rose gold",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 4,
                titleUrl: "#",
              },
              {
                label: "Platinum",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 5,
                titleUrl: "#",
              },
            ],
            sequence: 2,
            tabs: "WOMEN",
            isClickable: false,
          },
          {
            label: "Shop by style",
            isLeftAlign: true,
            isClickable: false,
            linkShowAll: {
              show: true,
              label: "View all styles",
              labelLink: "#",
            },
            link: [
              {
                label: "Plain",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 1,
                titleUrl: "#",
              },
              {
                label: "Diamond",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 2,
                titleUrl: "#",
              },
              {
                label: "Textured",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 5,
                titleUrl: "#",
              },
            ],
            sequence: 1,
            tabs: "MEN",
          },
          {
            label: "Shop by metal",
            isLeftAlign: true,
            isClickable: false,
            linkShowAll: {
              show: true,
              label: "View all metals",
              labelLink: "#",
            },
            link: [
              {
                label: "Silver",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 1,
                titleUrl: "#",
              },
              {
                label: "White gold",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 2,
                titleUrl: "#",
              },
              {
                label: "Yellow gold",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 3,
                titleUrl: "#",
              },
              {
                label: "Rose gold",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 4,
                titleUrl: "#",
              },
              {
                label: "Platinum",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 5,
                titleUrl: "#",
              },
            ],
            sequence: 2,
            tabs: "MEN",
          },
          {
            label: "Explore",
            isLeftAlign: true,
            isClickable: false,
            linkShowAll: {
              show: false,
              label: "",
            },
            link: [
              {
                label: "Bestsellers",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 1,
                titleUrl: "#",
              },
              {
                label: "New arrivals",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 2,
                titleUrl: "#",
              },
              {
                label: "Quick delivery",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 3,
                titleUrl: "#",
              },
              {
                label: "Bespoke design",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 4,
                titleUrl: "#",
              },
            ],
            sequence: 5,
          },
        ],
        additionalLink: [
          {
            label: "How to choose the perfect wedding ring",
            link: "#",
            sequence: 1,
            icon: false,
          },
          {
            label: "Get expert advice",
            link: "#",
            sequence: 2,
            icon: false,
          },
        ],
      },
      {
        id: 1,
        label: "Jewellery",
        link: "/gemstone-jewellery-listing",
        type: "1",
        showImage: true,
        imageCta: "#",
        imageUrl: "/assets/images/megamenu-banner.png",
        section: [
          {
            label: "EARRINGS",
            isLeftAlign: true,
            isClickable: true,
            linkShowAll: {
              show: true,
              label: "View all earrings",
              labelLink: "#",
            },
            link: [
              {
                label: "Stud",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 1,
                titleUrl: "#",
              },
              {
                label: "Hoops",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 2,
                titleUrl: "#",
              },
              {
                label: "Halo",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 3,
                titleUrl: "#",
              },
              {
                label: "Everyday",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 4,
                titleUrl: "#",
              },
              {
                label: "Statement",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 5,
                titleUrl: "#",
              },
              {
                label: "Drop",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 6,
                titleUrl: "#",
              },
              {
                label: "Gemstone",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 7,
                titleUrl: "#",
              },
              {
                label: "Coloured diamonds",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 8,
                titleUrl: "#",
              },
              {
                label: "View all earrings",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 9,
                titleUrl: "#",
              },
            ],
            sequence: 1,
            labelLink: "#",
          },
          {
            label: "NECKLACES",
            isLeftAlign: true,
            isClickable: true,
            linkShowAll: {
              show: true,
              label: "View all necklaces",
              labelLink: "#",
            },
            link: [
              {
                label: "Solitaire",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 1,
                titleUrl: "#",
              },
              {
                label: "Everyday",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 2,
                titleUrl: "#",
              },
              {
                label: "Halo",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 3,
                titleUrl: "#",
              },
              {
                label: "Tennis",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 4,
                titleUrl: "#",
              },
              {
                label: "Cluster",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 5,
                titleUrl: "#",
              },
              {
                label: "Gemstone",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 6,
                titleUrl: "#",
              },
              {
                label: "Coloured diamonds",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 7,
                titleUrl: "#",
              },
            ],
            sequence: 2,
            labelLink: "#",
          },
          {
            label: "BRACELETS",
            isLeftAlign: true,
            isClickable: true,
            linkShowAll: {
              show: true,
              label: "View all bracelets",
              labelLink: "#",
            },
            link: [
              {
                label: "Tennis",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 1,
                titleUrl: "#",
              },
              {
                label: "Everyday",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 2,
                titleUrl: "#",
              },
              {
                label: "Bangle",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 3,
                titleUrl: "#",
              },
              {
                label: "Statement",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 4,
                titleUrl: "#",
              },
              {
                label: "Gemstone",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 5,
                titleUrl: "#",
              },
            ],
            sequence: 3,
            labelLink: "#",
          },
          {
            label: "Explore",
            isLeftAlign: false,
            isClickable: true,
            linkShowAll: {
              show: false,
              label: "",
            },
            link: [
              {
                label: "Bestsellers",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: false,
                sequence: 1,
                titleUrl: "#",
              },
              {
                label: "New arrivals",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: false,
                sequence: 2,
                titleUrl: "#",
              },
              {
                label: "Quick delivery",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: false,
                sequence: 3,
                titleUrl: "#",
              },
              {
                label: "Bespoke design",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: false,
                sequence: 4,
                titleUrl: "#",
              },
            ],
            sequence: 4,
            labelLink: "#",
          },
          {
            label: "Shop by price",
            isLeftAlign: false,
            isClickable: true,
            linkShowAll: {
              show: true,
              label: "Get expert advice",
              labelLink: "#",
            },
            link: [
              {
                label: "Under £500",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: false,
                sequence: 1,
                titleUrl: "#",
              },
              {
                label: "£500 -  £1,000",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: false,
                sequence: 2,
                titleUrl: "#",
              },
              {
                label: "£500 -  £1,000",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: false,
                sequence: 3,
                titleUrl: "#",
              },
              {
                label: "£2,500+",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: false,
                sequence: 4,
                titleUrl: "#",
              },
            ],
            sequence: 5,
            labelLink: "#",
          },
        ],
        linkShowAll: {
          show: true,
          label: "",
        },
        tabValues: [
          {
            tabValue: "",
          },
        ],
        showTabs: false,
        sequence: 4,
      },
      {
        id: 1,
        label: "Gifts",
        link: "/gifting",
        type: "1",
        showImage: true,
        imageCta: "#",
        imageUrl: "/assets/images/megamenu-banner.png",
        section: [
          {
            label: "Most gifted",
            isLeftAlign: true,
            isClickable: true,
            linkShowAll: {
              show: false,
              label: "",
            },
            link: [
              {
                label: "Rings",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 1,
                titleUrl: "#",
              },
              {
                label: "Earrings",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 2,
                titleUrl: "#",
              },
              {
                label: "Bracelets",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 3,
                titleUrl: "#",
              },
              {
                label: "Necklaces",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 4,
                titleUrl: "#",
              },
            ],
            sequence: 1,
            labelLink: "#",
          },
          {
            label: "Shop by occasion",
            isLeftAlign: true,
            isClickable: true,
            linkShowAll: {
              show: false,
              label: "",
            },
            link: [
              {
                label: "Birthday",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 1,
                titleUrl: "#",
              },
              {
                label: "Anniversary",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 2,
                titleUrl: "#",
              },
              {
                label: "Milestone",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 3,
                titleUrl: "#",
              },
            ],
            sequence: 2,
            labelLink: "#",
          },
          {
            label: "Birthstones",
            isLeftAlign: true,
            isClickable: true,
            linkShowAll: {
              show: true,
              label: "View all",
              labelLink: "#",
            },
            link: [
              {
                label: "Amethyst",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 1,
                titleUrl: "#",
              },
              {
                label: "Aquamarine",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 2,
                titleUrl: "#",
              },
              {
                label: "Garnet",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 3,
                titleUrl: "#",
              },
              {
                label: "Sapphire",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 4,
                titleUrl: "#",
              },
              {
                label: "Diamond",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 5,
                titleUrl: "#",
              },
              {
                label: "Emerald",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 6,
                titleUrl: "#",
              },
            ],
            sequence: 3,
            labelLink: "#",
          },
          {
            label: "Explore",
            isLeftAlign: true,
            isClickable: true,
            linkShowAll: {
              show: false,
              label: "",
            },
            link: [
              {
                label: "Most gifted",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 1,
                titleUrl: "#",
              },
              {
                label: "New arrivals ",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 2,
                titleUrl: "#",
              },
              {
                label: "Quick  delivery",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 3,
                titleUrl: "#",
              },
              {
                label: "Bespoke design  ",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 4,
                titleUrl: "#",
              },
            ],
            sequence: 4,
            labelLink: "#",
          },
          {
            label: "Shop for",
            isLeftAlign: true,
            isClickable: true,
            linkShowAll: {
              show: false,
              label: "",
            },
            link: [
              {
                label: "For her",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 1,
                titleUrl: "#",
              },
              {
                label: "For him",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 2,
                titleUrl: "#",
              },
              {
                label: "For girlfriend ",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 3,
                titleUrl: "#",
              },
              {
                label: "For friend",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 4,
                titleUrl: "#",
              },
            ],
            sequence: 5,
            labelLink: "#",
          },
          {
            label: "Shop by price",
            isLeftAlign: true,
            isClickable: true,
            linkShowAll: {
              show: false,
              label: "",
            },
            link: [
              {
                label: "Under £500",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 1,
                titleUrl: "#",
              },
              {
                label: "£500 -  £1,000",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 2,
                titleUrl: "#",
              },
              {
                label: "£1,000 -  £2,500",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 3,
                titleUrl: "#",
              },
              {
                label: "£2,500+",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 4,
                titleUrl: "#",
              },
            ],
            sequence: 6,
            labelLink: "#",
          },
        ],
        linkShowAll: {
          show: true,
          label: "",
        },
        tabValues: [
          {
            tabValue: "",
          },
        ],
        showTabs: false,
        sequence: 5,
        additionalLink: [
          {
            label: "Our gift guide",
            link: "#",
            sequence: 1,
            icon: false,
          },
          {
            label: "Get expert advice",
            link: "#",
            sequence: 2,
            icon: false,
          },
        ],
      },
      {
        id: 1,
        label: "Education",
        link: "/education",
        type: "1",
        showImage: false,
        imageCta: "#",
        imageUrl: "",
        section: [
          {
            label: "Guides",
            isLeftAlign: true,
            isClickable: true,
            linkShowAll: {
              show: false,
              label: "",
            },
            link: [
              {
                label: "Diamond guide",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: false,
                sequence: 1,
                titleUrl: "/education/diamond-guide",
              },
              {
                label: "Metal guide",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: false,
                sequence: 2,
                titleUrl: "/education/metal-guide",
              },
              {
                label: "Ring size guide",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: false,
                sequence: 3,
                titleUrl: "/education/ring-size-guide",
              },
              {
                label: "Jewellery care",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: false,
                sequence: 4,
                titleUrl: "/jewellery-care",
              },
              {
                label: "Hallmarks",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: false,
                sequence: 5,
                titleUrl: "#",
              },
              {
                label: "Find my ring size",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: false,
                sequence: 6,
                titleUrl: "#",
              },
            ],
            sequence: 1,
            labelLink: "#",
          },
          {
            label: "Blog",
            isLeftAlign: false,
            isClickable: false,
            linkShowAll: {
              show: true,
              label: "View all",
              labelLink: "#",
            },
            link: [
              {
                label:
                  "What is better for an engagement ring — White gold or silver?",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: false,
                sequence: 1,
                titleUrl: "#",
              },
              {
                label: "How to size an engagement ring",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: false,
                sequence: 2,
                titleUrl: "#",
              },
              {
                label: "Best places to propose in London",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: false,
                sequence: 3,
                titleUrl: "#",
              },
            ],
            sequence: 2,
          },
          {
            label: "About us",
            isLeftAlign: false,
            isClickable: true,
            linkShowAll: {
              show: false,
              label: "",
            },
            link: [
              {
                label: "Our story",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: false,
                sequence: 1,
                titleUrl: "#",
              },
              {
                label: "Customer Reviews",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: false,
                sequence: 2,
                titleUrl: "#",
              },
              {
                label: "FAQ's",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: false,
                sequence: 3,
                titleUrl: "#",
              },
            ],
            sequence: 3,
          },
          {
            label: "Contact us",
            isLeftAlign: false,
            isClickable: true,
            linkShowAll: {
              show: false,
              label: "",
            },
            link: [
              {
                label: "020 7660 1529",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: false,
                sequence: 1,
                titleUrl: "020 7660 1529",
              },
              {
                label: "service@austenblake.com",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: false,
                sequence: 2,
                titleUrl: "service@austenblake.com",
              },
            ],
            sequence: 4,
            labelLink: "#",
          },
        ],
        linkShowAll: {
          show: true,
          label: "",
        },
        tabValues: [
          {
            tabValue: "",
          },
        ],
        showTabs: false,
        sequence: 6,
      },
      {
        id: 1,
        label: "Visit our stores",
        link: "#",
        type: "2",
        showImage: true,
        imageCta: "#",
        imageUrl: "/assets/images/visit-our-store-dbanner.png",
        section: [
          {
            label: "Visit us",
            isLeftAlign: false,
            isClickable: true,
            linkShowAll: {
              show: false,
              label: "",
            },
            link: [
              {
                label: "London",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: false,
                sequence: 1,
                titleUrl: "#",
              },
              {
                label: "Nottingham",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: false,
                sequence: 2,
                titleUrl: "#",
              },
              {
                label: "Chester",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: false,
                sequence: 3,
                titleUrl: "#",
              },
              {
                label: "Manchester",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: false,
                sequence: 4,
                titleUrl: "#",
              },
              {
                label: "Edinburgh",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: false,
                sequence: 5,
                titleUrl: "#",
              },
              {
                label: "Norwich",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: false,
                sequence: 6,
                titleUrl: "#",
              },
              {
                label: "Leeds",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: false,
                sequence: 7,
                titleUrl: "#",
              },
              {
                label: "Birmingham",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: false,
                sequence: 8,
                titleUrl: "#",
              },
              {
                label: "Southampton",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: false,
                sequence: 9,
                titleUrl: "#",
              },
              {
                label: "Liverpool",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: false,
                sequence: 10,
                titleUrl: "#",
              },
              {
                label: "Newcastle",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: false,
                sequence: 11,
                titleUrl: "#",
              },
              {
                label: "Bristol",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: false,
                sequence: 12,
                titleUrl: "#",
              },
              {
                label: "Sheffield",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: false,
                sequence: 13,
                titleUrl: "#",
              },
              {
                label: "Belfast",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: false,
                sequence: 14,
                titleUrl: "#",
              },
              {
                label: "Glasgow",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: false,
                sequence: 15,
                titleUrl: "#",
              },
              {
                label: "Cardiff",
                showIcon: false,
                iconUrl: "#",
                link: "#",
                isMobile: false,
                sequence: 16,
                titleUrl: "#",
              },
            ],
            sequence: 1,
            labelLink: "#",
          },
          {
            label: "Contact us",
            isLeftAlign: false,
            isClickable: true,
            linkShowAll: {
              show: false,
              label: "",
            },
            link: [
              {
                label: "020 7660 1529",
                showIcon: true,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 1,
                titleUrl: "020 7660 1529",
              },
              {
                label: "service@austenblake.com",
                showIcon: true,
                iconUrl: "#",
                link: "#",
                isMobile: true,
                sequence: 2,
                titleUrl: "service@austenblake.com",
              },
            ],
            sequence: 2,
            labelLink: "#",
          },
        ],
        linkShowAll: {
          show: true,
          label: "",
        },
        tabValues: [
          {
            tabValue: "",
          },
        ],
        showTabs: false,
        sequence: 7,
        additionalLink: [
          {
            label: "Book an appointment",
            link: "#book-appointment",
            sequence: 1,
            icon: true,
            iconLink: "/assets/icons/raw-svgs/calendar-schedule.svg",
          },
          {
            label: "Video appointment",
            link: "#virtual-appointment",
            sequence: 2,
            icon: true,
            iconLink: "/assets/icons/raw-svgs/record-videos-camera.svg",
          },
        ],
      },
      {
        id: 1,
        label: "Contact Us",
        link: "/abc",
        type: "1",
        showImage: false,
        imageCta: "#",
        imageUrl: "",
        section: [],
        additionalLink: [],
        linkShowAll: {
          show: true,
          label: "",
        },
        tabValues: [
          {
            tabValue: "",
          },
        ],
        showTabs: false,
        sequence: 8,
      },
    ],
    socialMedias: [],
    certificates: [],
    otherLinks: [],
    siteLogo: "/assets/images/austen-and-blake-logo.png",
    section: [],
    id: "b1d704d2-3d67-43ca-aea8-629a3b833e6f",
    defaultSelect: false,
    isDefault: false,
  },
];
