name: Build and Deploy to GKE
on:
  push:
    branches:
      - sprint-84
env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: nj-cluster # Add your cluster name here.
  GKE_ZONE: europe-west2 # Add your cluster zone here.
  DEPLOYMENT_NAME: customer-ui-dev # Add your deployment name here.
  IMAGE: customer-ui-dev
  GKE_NAMESPACE: customer-ui
  APP_ENVIRONMENT: development
jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Setup gcloud-CLI
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'
      # Configure Docker to use the gcloud command-line tool as a credential
      # helper for authentication
      - run: |-
          gcloud --quiet auth configure-docker europe-docker.pkg.dev
      # Get the GKE credentials so we can deploy to the cluster
      - uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
      # Build the Docker image
      - name: Build
        run: |-
          docker build \
            --tag "europe-docker.pkg.dev/$PROJECT_ID/forge/$IMAGE:$GITHUB_SHA" \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            --build-arg GITHUB_REF="$GITHUB_REF" \
            --build-arg APP_ENVIRONMENT="$APP_ENVIRONMENT" \
            --file ./Dockerfile-dev .

      # Push the Docker image to Google Container Registry
      - name: Publish
        run: |-
          docker push "europe-docker.pkg.dev/$PROJECT_ID/forge/$IMAGE:$GITHUB_SHA"

      # Set up kustomize
      - name: Set up Kustomize
        run: |-
          curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
          chmod u+x ./kustomize
          mv ./kustomize ~/

      # Deploy the Docker image to the GKE cluster
      - name: Deploy
        run: |-
          cd ci/k8s/dev
          ~/kustomize edit set image nj/customer-ui-dev=europe-docker.pkg.dev/$PROJECT_ID/forge/$IMAGE:$GITHUB_SHA
          ~/kustomize build | kubectl -n $GKE_NAMESPACE apply -f -